export const PAGINATION = {
  GRID_PAGE_SIZE: 24,
  GRID_COLUMNS: 6,
  GRID_ROWS: 4,
};

export const ANIMATION = {
  HEADLINE_INTERVAL: 5000,
  HEADLINE_TRANSITION: 500,
  HEADLINE_LEFT_DELAY: 0,
  HEADLINE_RIGHT_DELAY: 1000,
};

export const RECENT_NEWS = {
  LEFT_NEWS_START: 0,
  RIGHT_NEWS_START: 5,
};
